# Generated by Django 5.0.6 on 2025-12-20 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_emergency_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('relationship', models.CharField(max_length=50, verbose_name='Qarindoshlik')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Asosiy kontakt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favqulodda kontakt',
                'verbose_name_plural': 'Favqulodda kontaktlar',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencySOS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.TextField(blank=True, default='', verbose_name='Manzil')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('responded', 'Javob berildi'), ('resolved', 'Hal qilindi'), ('cancelled', 'Bekor qilindi')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('notified_contacts', models.JSONField(blank=True, default=list)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "SOS so'rov",
                'verbose_name_plural': "SOS so'rovlar",
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('relationship', models.CharField(choices=[('child', 'Farzand'), ('spouse', "Turmush o'rtog'i"), ('parent', 'Ota-ona'), ('sibling', 'Aka-uka/opa-singil'), ('other', 'Boshqa')], max_length=20, verbose_name='Qarindoshlik')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('blood_type', models.CharField(blank=True, default='', max_length=5, verbose_name='Qon guruhi')),
                ('allergies', models.JSONField(blank=True, default=list, verbose_name='Allergiyalar')),
                ('chronic_conditions', models.JSONField(blank=True, default=list, verbose_name='Surunkali kasalliklar')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izohlar')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Oila a'zosi",
                'verbose_name_plural': "Oila a'zolari",
                'ordering': ['-created_at'],
            },
        ),
    ]
