# Generated by Django 5.2.8 on 2025-12-05 04:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Uzbekistan', max_length=100)),
                ('aqi', models.IntegerField()),
                ('main_pollutant', models.CharField(default='pm25', max_length=10)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Havo sifati yozuvi',
                'verbose_name_plural': 'Havo sifati yozuvlari',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAirQualityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(default='Tashkent', max_length=100)),
                ('alert_threshold', models.IntegerField(default=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('has_asthma', models.BooleanField(default=False)),
                ('has_heart_disease', models.BooleanField(default=False)),
                ('has_allergies', models.BooleanField(default=False)),
                ('has_lung_disease', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi ogohlantirishi',
                'verbose_name_plural': 'Foydalanuvchi ogohlantirishlari',
            },
        ),
    ]
