# Generated by Django 5.2.7 on 2025-12-10 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('ringing', 'Jiringlamoqda'), ('active', 'Faol'), ('ended', 'Tugadi'), ('missed', 'Javobsiz'), ('declined', 'Rad etildi')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('caller_offer', models.TextField(blank=True)),
                ('receiver_answer', models.TextField(blank=True)),
                ('ice_candidates', models.JSONField(default=list)),
                ('is_video', models.BooleanField(default=True)),
                ('call_quality', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls', to='chat.chatroom')),
            ],
            options={
                'verbose_name': "Video qo'ng'iroq",
                'verbose_name_plural': "Video qo'ng'iroqlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
