# Generated by Django 5.2.8 on 2025-12-03 04:54

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Qabul', 'verbose_name_plural': 'Qabullar'},
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-record_date', '-created_at'], 'verbose_name': 'Tibbiy yozuv', 'verbose_name_plural': 'Tibbiy tarix'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Retsept', 'verbose_name_plural': 'Retseptlar'},
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medical_record',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medication_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='attachments',
            field=models.JSONField(blank=True, default=list, verbose_name='Biriktirmalar'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description',
            field=models.TextField(default='', verbose_name='Tavsif'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_confidential',
            field=models.BooleanField(default=False, verbose_name='Maxfiy'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_date',
            field=models.DateField(default=datetime.date(2025, 12, 3), verbose_name='Sana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('examination', "Ko'rik"), ('diagnosis', 'Tashxis'), ('treatment', 'Davolash'), ('lab_result', 'Laboratoriya natijasi'), ('imaging', 'Tasvir (rentgen, UZI, MRT)'), ('vaccination', 'Emlash'), ('allergy', 'Allergiya'), ('surgery', 'Jarrohlik'), ('hospitalization', 'Kasalxonaga yotqizish'), ('note', 'Eslatma')], default='examination', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='title',
            field=models.CharField(default='Tibbiy yozuv', max_length=255, verbose_name='Sarlavha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vitals',
            field=models.JSONField(blank=True, default=dict, verbose_name="Vital ko'rsatkichlar"),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(default='Tashxis', verbose_name='Tashxis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='medications',
            field=models.JSONField(default=list, verbose_name='Dorilar'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, verbose_name="Qo'shimcha eslatmalar"),
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Amal qilish muddati'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Eslatmalar'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, verbose_name='Simptomlar'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True, verbose_name="Ko'rsatmalar"),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen', models.CharField(max_length=255, verbose_name='Allergen')),
                ('reaction', models.TextField(verbose_name='Reaktsiya')),
                ('severity', models.CharField(choices=[('mild', 'Yengil'), ('moderate', "O'rtacha"), ('severe', "Og'ir")], default='moderate', max_length=10)),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allergiya',
                'verbose_name_plural': 'Allergiyalar',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=255, verbose_name='Kasallik nomi')),
                ('diagnosed_date', models.DateField(blank=True, null=True, verbose_name='Tashxis sanasi')),
                ('current_status', models.CharField(default='active', max_length=50, verbose_name='Holati')),
                ('medications', models.JSONField(blank=True, default=list, verbose_name='Doimiy dorilar')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_condition_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surunkali kasallik',
                'verbose_name_plural': 'Surunkali kasalliklar',
                'ordering': ['-created_at'],
            },
        ),
    ]
