# Generated by Django 5.2.8 on 2025-12-03 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-record_date', '-created_at'], 'verbose_name': 'Tibbiy yozuv', 'verbose_name_plural': 'Tibbiy yozuvlar'},
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, default='Konsultatsiya'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_allergies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='severity',
            field=models.CharField(choices=[('mild', 'Yengil'), ('moderate', "O'rtacha"), ('severe', "Og'ir"), ('life_threatening', 'Hayotga xavfli')], default='moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan'), ('no_show', 'Kelmadi')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='chroniccondition',
            name='current_status',
            field=models.CharField(choices=[('active', 'Faol'), ('managed', 'Nazorat ostida'), ('resolved', 'Davolangan'), ('remission', 'Remissiyada')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='chroniccondition',
            name='diagnosed_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tashxis qo'yilgan sana"),
        ),
        migrations.AlterField(
            model_name='chroniccondition',
            name='medications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chroniccondition',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_chronic_conditions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_medical_records', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='is_confidential',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('consultation', 'Konsultatsiya'), ('diagnosis', 'Tashxis'), ('lab_result', 'Laboratoriya natijasi'), ('imaging', 'Tasvir (rentgen, MRT)'), ('surgery', 'Jarrohlik'), ('vaccination', 'Emlash'), ('procedure', 'Protsedura'), ('follow_up', 'Kuzatuv'), ('other', 'Boshqa')], default='consultation', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='vitals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_prescriptions', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Izohlar'),
        ),
    ]
