# Generated by Django 5.0.6 on 2025-12-20 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_appointment_date_a3fbbd_idx_and_more'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(choices=[('blood', 'Qon tahlili'), ('urine', 'Siydik tahlili'), ('stool', 'Najas tahlili'), ('xray', 'Rentgen'), ('ultrasound', 'UZI'), ('mri', 'MRT'), ('ct', 'KT'), ('ecg', 'EKG'), ('endoscopy', 'Endoskopiya'), ('biopsy', 'Biopsiya'), ('allergy', 'Allergiya testi'), ('hormone', 'Gormon tahlili'), ('genetic', 'Genetik test'), ('other', 'Boshqa')], max_length=20, verbose_name='Tahlil turi')),
                ('test_name', models.CharField(max_length=200, verbose_name='Tahlil nomi')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('date', models.DateField(verbose_name='Sana')),
                ('time', models.TimeField(verbose_name='Vaqt')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('status', models.CharField(choices=[('booked', 'Bron qilingan'), ('confirmed', 'Tasdiqlangan'), ('in_progress', 'Jarayonda'), ('completed', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='booked', max_length=20)),
                ('results', models.JSONField(blank=True, default=dict, verbose_name='Natijalar')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/%Y/%m/', verbose_name='Natija fayli')),
                ('result_summary', models.TextField(blank=True, default='', verbose_name='Natija xulosasi')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('doctor_notes', models.TextField(blank=True, default='', verbose_name='Shifokor izohi')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Shoshilinch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='doctors.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laboratoriya tahlili',
                'verbose_name_plural': 'Laboratoriya tahlillari',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['user', 'status'], name='appointment_user_id_fd2799_idx'), models.Index(fields=['date', 'hospital'], name='appointment_date_024ec5_idx')],
            },
        ),
    ]
