# Generated by Django 5.2.8 on 2025-11-30 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tolangan'), ('cancelled', 'Bekor qilingan'), ('failed', 'Xatolik'), ('refunded', 'Qaytarilgan')], default='pending', max_length=20)),
                ('payment_type', models.CharField(choices=[('appointment', 'Qabulga yozilish'), ('consultation', 'Online konsultatsiya'), ('subscription', 'Obuna')], default='appointment', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tolov',
                'verbose_name_plural': 'Tolovlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_trans_id', models.CharField(max_length=255)),
                ('service_id', models.CharField(max_length=255)),
                ('merchant_trans_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('action', models.IntegerField()),
                ('error', models.IntegerField(default=0)),
                ('error_note', models.CharField(blank=True, max_length=255)),
                ('sign_time', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_transactions', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Click Transaksiya',
                'verbose_name_plural': 'Click Transaksiyalar',
            },
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_id', models.CharField(max_length=255, unique=True)),
                ('state', models.IntegerField(choices=[(1, 'Yaratilgan'), (2, 'Tasdiqlangan'), (-1, 'Bekor qilingan (timeout)'), (-2, 'Bekor qilingan (admin)')], default=1)),
                ('create_time', models.BigIntegerField()),
                ('perform_time', models.BigIntegerField(default=0)),
                ('cancel_time', models.BigIntegerField(default=0)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payme_transactions', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payme Transaksiya',
                'verbose_name_plural': 'Payme Transaksiyalar',
            },
        ),
    ]
