# Generated by Django 5.2.8 on 2025-11-29 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConsultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('medical_history', models.JSONField(default=list)),
                ('ai_analysis', models.JSONField()),
                ('possible_conditions', models.JSONField(default=list)),
                ('urgency_level', models.IntegerField(choices=[(1, 'Juda past'), (2, 'Past'), (3, "O'rtacha"), (4, "O'rtachadan yuqori"), (5, 'Yuqori'), (6, 'Juda yuqori'), (7, 'Shoshilinch'), (8, 'Juda shoshilinch'), (9, 'Kritik'), (10, 'Hayotiy xavf')])),
                ('recommended_specialist', models.CharField(max_length=100)),
                ('first_aid_tips', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Konsultatsiya',
                'verbose_name_plural': 'AI Konsultatsiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
