# Generated by Django 5.2.8 on 2025-12-03 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=255, verbose_name="Nomi (O'zbekcha)")),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('icd_code', models.CharField(blank=True, max_length=20, verbose_name='ICD-10 kodi')),
                ('category', models.CharField(max_length=100, verbose_name='Kategoriya')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('common_symptoms', models.JSONField(default=list, verbose_name='Umumiy alomatlar')),
                ('recommended_specialization', models.CharField(max_length=100, verbose_name='Tavsiya etilgan mutaxassis')),
                ('urgency_level', models.CharField(choices=[('low', 'Past'), ('normal', 'Normal'), ('high', 'Yuqori'), ('emergency', 'Shoshilinch')], default='normal', max_length=20)),
                ('treatment_overview', models.TextField(blank=True, verbose_name='Davolash haqida')),
                ('prevention_tips', models.JSONField(default=list, verbose_name='Oldini olish maslahatlari')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kasallik',
                'verbose_name_plural': 'Kasalliklar',
                'ordering': ['category', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=255, verbose_name="Nomi (O'zbekcha)")),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Nomi (Ruscha)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Nomi (Inglizcha)')),
                ('icon', models.CharField(default='🩺', max_length=10, verbose_name='Emoji')),
                ('category', models.CharField(choices=[('bosh', 'Bosh'), ('kokrak', "Ko'krak"), ('qorin', 'Qorin'), ('oyoq_qol', "Oyoq-Qo'l"), ('teri', 'Teri'), ('umumiy', 'Umumiy'), ('ruhiy', 'Ruhiy')], max_length=20, verbose_name='Kategoriya')),
                ('body_part', models.CharField(blank=True, max_length=100, verbose_name='Tana qismi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('related_conditions', models.JSONField(default=list, verbose_name="Bog'liq kasalliklar")),
                ('related_specializations', models.JSONField(default=list, verbose_name="Bog'liq mutaxassisliklar")),
                ('is_emergency', models.BooleanField(default=False, verbose_name='Shoshilinch')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alomat',
                'verbose_name_plural': 'Alomatlar',
                'ordering': ['category', 'name_uz'],
            },
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='appointment_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='final_recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='home_treatment',
            field=models.JSONField(default=list, verbose_name='Uy sharoitida davolash'),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='messages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='suggested_doctor_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aiconsultation',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiconsultation',
            name='ai_analysis',
            field=models.TextField(blank=True, verbose_name='AI tahlili'),
        ),
        migrations.AlterField(
            model_name='aiconsultation',
            name='first_aid_tips',
            field=models.JSONField(default=list, verbose_name='Birinchi yordam'),
        ),
        migrations.AlterField(
            model_name='aiconsultation',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='aiconsultation',
            name='medical_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aiconsultation',
            name='possible_conditions',
            field=models.JSONField(default=list, verbose_name='Ehtimoliy kasalliklar'),
        ),
        migrations.AlterField(
            model_name='aiconsultation',
            name='recommended_specialist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aiconsultation',
            name='symptoms',
            field=models.TextField(verbose_name='Alomatlar'),
        ),
        migrations.AlterField(
            model_name='aiconsultation',
            name='urgency_level',
            field=models.CharField(choices=[('past', 'Past'), ("o'rta", "O'rtacha"), ('yuqori', 'Yuqori'), ('jiddiy', 'Jiddiy')], default="o'rta", max_length=20),
        ),
        migrations.AlterField(
            model_name='aiconsultation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aiconsultation',
            name='warnings',
            field=models.JSONField(default=list, verbose_name='Ogohlantirishlar'),
        ),
        migrations.CreateModel(
            name='SymptomCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms', models.JSONField(default=list, verbose_name='Alomatlar')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yosh')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='Jins')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Davomiyligi')),
                ('severity', models.CharField(choices=[('mild', 'Yengil'), ('moderate', "O'rtacha"), ('severe', "Og'ir")], default='moderate', max_length=20, verbose_name='Darajasi')),
                ('additional_info', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot")),
                ('ai_response', models.JSONField(default=dict, verbose_name='AI javobi')),
                ('is_emergency', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptom_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alomatlar tekshiruvi',
                'verbose_name_plural': 'Alomatlar tekshiruvlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='symptom_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='ai_service.symptomcheck'),
        ),
    ]
