# Generated by Django 5.2.8 on 2025-12-05 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('hospital_type', models.CharField(choices=[('hospital', 'Kasalxona'), ('clinic', 'Klinika'), ('pharmacy', 'Dorixona'), ('laboratory', 'Laboratoriya'), ('dental', 'Stomatologiya')], default='hospital', max_length=20)),
                ('address', models.TextField(verbose_name='Manzil')),
                ('city', models.CharField(default='Toshkent', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('is_24_hours', models.BooleanField(default=False, verbose_name='24 soat')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('services', models.JSONField(blank=True, default=list)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, upload_to='hospitals/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kasalxona',
                'verbose_name_plural': 'Kasalxonalar',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('document_type', models.CharField(choices=[('analysis', 'Tahlil natijasi'), ('prescription', 'Retsept'), ('xray', 'Rentgen'), ('mri', 'MRT'), ('ultrasound', 'UZI'), ('certificate', 'Spravka'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='medical_documents/%Y/%m/', verbose_name='Fayl')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('doctor_name', models.CharField(blank=True, max_length=200, verbose_name='Shifokor')),
                ('hospital_name', models.CharField(blank=True, max_length=200, verbose_name='Shifoxona')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Hujjat sanasi')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('is_important', models.BooleanField(default=False, verbose_name='Muhim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tibbiy hujjat',
                'verbose_name_plural': 'Tibbiy hujjatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200, verbose_name='Dori nomi')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dozasi')),
                ('frequency', models.CharField(choices=[('once', 'Bir marotaba'), ('daily', 'Har kuni'), ('twice_daily', 'Kuniga 2 marta'), ('three_times', 'Kuniga 3 marta'), ('weekly', 'Haftada bir'), ('custom', 'Maxsus')], default='daily', max_length=20)),
                ('times', models.JSONField(default=list, verbose_name='Vaqtlar')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('paused', "To'xtatilgan"), ('completed', 'Yakunlangan')], default='active', max_length=20)),
                ('with_food', models.BooleanField(default=False, verbose_name='Ovqat bilan')),
                ('before_food', models.BooleanField(default=False, verbose_name='Ovqatdan oldin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dori eslatmasi',
                'verbose_name_plural': 'Dori eslatmalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(verbose_name='Rejalashtirilgan vaqt')),
                ('actual_time', models.DateTimeField(blank=True, null=True, verbose_name='Haqiqiy vaqt')),
                ('status', models.CharField(choices=[('taken', 'Ichildi'), ('skipped', "O'tkazib yuborildi"), ('snoozed', 'Keyinga qoldirildi')], default='taken', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medicines.medicinereminder')),
            ],
            options={
                'verbose_name': 'Eslatma tarixi',
                'verbose_name_plural': 'Eslatma tarixi',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='HospitalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='medicines.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'unique_together': {('hospital', 'user')},
            },
        ),
    ]
