# Generated by Django 5.0.6 on 2025-12-20 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_labtest'),
        ('medicines', '0002_hospital_medicaldocument_medicinereminder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('items', models.JSONField(default=list, verbose_name='Buyurtma tarkibi')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jami summa')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Olib ketish'), ('delivery', 'Yetkazish')], default='pickup', max_length=20)),
                ('delivery_address', models.TextField(blank=True, default='', verbose_name='Yetkazish manzili')),
                ('delivery_phone', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('preparing', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('estimated_ready_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='medicines.pharmacy')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='appointments.prescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retsept buyurtmasi',
                'verbose_name_plural': 'Retsept buyurtmalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
